server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${esp.datasource.driver-class-name}
      url: jdbc:mysql://${esp.datasource.host}:${esp.datasource.port}/${esp.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${esp.datasource.username}
      password: ${esp.datasource.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.enterprise_school_platform.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      enterprise_school_platform:
        mapper: debug
        service: info
        controller: info

esp:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: X7kP9mN2qL8vB3wE5rT1yU6iO4pA0sD9fG7naiweilanlanmQ3wE6rT8yU0iO2pL4k
    # 设置jwt过期时间
    admin-ttl: 7200
    # 设置前端传递过来的令牌名称
    admin-token-name: token
